name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check:
    name: 代码检查
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 类型检查
        run: npm run type-check

      - name: 代码检查
        run: npm run lint

  deploy-dev:
    name: 部署到开发环境
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/develop'
    environment:
      name: development
      url: ${{ steps.deploy.outputs.endpoint }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 配置 AWS 凭证
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: 部署到 AWS (开发环境)
        id: deploy
        run: |
          npm run deploy:dev
          ENDPOINT=$(serverless info --stage dev | grep "endpoint:" | awk '{print $2}')
          echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT

      - name: 通知部署成功
        run: |
          echo "✅ 开发环境部署成功！"
          echo "API 端点: ${{ steps.deploy.outputs.endpoint }}"

  deploy-prod:
    name: 部署到生产环境
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: ${{ steps.deploy.outputs.endpoint }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 配置 AWS 凭证
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: 部署到 AWS (生产环境)
        id: deploy
        run: |
          npm run deploy:prod
          ENDPOINT=$(serverless info --stage prod | grep "endpoint:" | awk '{print $2}')
          echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT

      - name: 通知部署成功
        run: |
          echo "✅ 生产环境部署成功！"
          echo "API 端点: ${{ steps.deploy.outputs.endpoint }}"

      - name: 创建 GitHub Release（可选）
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
